import type { Metadata } from 'next';
import './globals.css';
import Header from './layout_components/header';
import Footer from './layout_components/footer';
import { app, analytics } from './utils/firebase';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
	return (
		<html lang='en'>
			<body
				className={`bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200 font-sans transition-colors duration-500 antialiased`}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
